version: '3'

services:
    api:
        container_name: django_test
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - '8001:8000'
        volumes:
            - .:/app

networks:
    default:
        external:
            name: mysql_default